// This code was almost entirely generated by Bing Copilot, an AI and has not been touched nor tested yet. 
// Do not expect it to work.

fun ErrorHandling() =
listeners {
onException { event, exception ->
    val message = when (exception) {
        is NumberFormatException -> "You must enter a number!"
        is CommandException -> "${exception.message}"
        else -> "An unexpected error occurred: ${exception.message}"
    }
    event.channel.createMessage(message ?: "An error occurred.")
}
}

class CommandException(message: String) : Exception(message)
